spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true
    drop-first: false
    default-schema: public
logging:
  level:
    root: INFO
    com.pismo.paymentpractice: DEBUG

