spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true
    drop-first: false
    default-schema: public
logging:
  level:
    root: INFO
    com.pismo.paymentpractice: DEBUG

server:
  port: 8000

